//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Localization.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InstallStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InstallStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roadkill.Core.Localization.Resx.InstallStrings", typeof(InstallStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank for you downloading Roadkill .NET Wiki engine. The installer writes the settings you enter here to the web.config file (and also the database). .
        /// </summary>
        public static string Page1_Label1 {
            get {
                return ResourceManager.GetString("Page1_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to proceed, first we need to test if you have write access to the web.config file. .
        /// </summary>
        public static string Page1_Label2 {
            get {
                return ResourceManager.GetString("Page1_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the web.config file..
        /// </summary>
        public static string Page1_WebConfig_Failure_Message {
            get {
                return ResourceManager.GetString("Page1_WebConfig_Failure_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web.config can be written to..
        /// </summary>
        public static string Page1_WebConfig_Success_Message {
            get {
                return ResourceManager.GetString("Page1_WebConfig_Success_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect:.
        /// </summary>
        public static string Page2_Error {
            get {
                return ResourceManager.GetString("Page2_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the wiki, which appears on certain themes and in signup emails (if enabled). .
        /// </summary>
        public static string Page2_Group1_Label {
            get {
                return ResourceManager.GetString("Page2_Group1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string Page2_Group1_Title {
            get {
                return ResourceManager.GetString("Page2_Group1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The full url of the wiki, which appears in signup and reset passwords emails (if enabled). Do not include the trailing slash. .
        /// </summary>
        public static string Page2_Group2_Label {
            get {
                return ResourceManager.GetString("Page2_Group2_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site url.
        /// </summary>
        public static string Page2_Group2_Title {
            get {
                return ResourceManager.GetString("Page2_Group2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to create the database first if you are using a named instance. Below are a few examples, use the second option is you are using shared hosting without any SQL Server hosting..
        /// </summary>
        public static string Page2_Group3_Label {
            get {
                return ResourceManager.GetString("Page2_Group3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example connection strings.
        /// </summary>
        public static string Page2_Group3_Label2 {
            get {
                return ResourceManager.GetString("Page2_Group3_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type.
        /// </summary>
        public static string Page2_Group3_Label3 {
            get {
                return ResourceManager.GetString("Page2_Group3_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure - try copying the SQLite.Interop.dll file from ~/App_Data/SQLiteBinaries to your bin folder..
        /// </summary>
        public static string Page2_Group3_SQLiteFailureMessage {
            get {
                return ResourceManager.GetString("Page2_Group3_SQLiteFailureMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite file copy failed.
        /// </summary>
        public static string Page2_Group3_SQLiteFailureTitle {
            get {
                return ResourceManager.GetString("Page2_Group3_SQLiteFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: to use SQLite you need to add another file to the /bin folder, as SQLite is distributed for both x86 and x64. &lt;a href=&quot;javascript:;&quot; id=&quot;sqlitecopy&quot;&gt;Click here to copy the file&lt;/a&gt;. If you experience any issues after this, delete &quot;SQLite.Interop.dll&quot; from your bin folder..
        /// </summary>
        public static string Page2_Group3_SQLiteInstructionsMessage {
            get {
                return ResourceManager.GetString("Page2_Group3_SQLiteInstructionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite: please read.
        /// </summary>
        public static string Page2_Group3_SQLiteInstructionsTitle {
            get {
                return ResourceManager.GetString("Page2_Group3_SQLiteInstructionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite should now be ready to use..
        /// </summary>
        public static string Page2_Group3_SQLiteSuccessMessage {
            get {
                return ResourceManager.GetString("Page2_Group3_SQLiteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite file copy success.
        /// </summary>
        public static string Page2_Group3_SQLiteSuccessTitle {
            get {
                return ResourceManager.GetString("Page2_Group3_SQLiteSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection string.
        /// </summary>
        public static string Page2_Group3_Title {
            get {
                return ResourceManager.GetString("Page2_Group3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Below are some required settings for Roadkill to work correctly. You can change these later via the settings page as an admin..
        /// </summary>
        public static string Page2_Label1 {
            get {
                return ResourceManager.GetString("Page2_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection is was successful..
        /// </summary>
        public static string Page2_Success {
            get {
                return ResourceManager.GetString("Page2_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the Active Directory server:.
        /// </summary>
        public static string Page3_AD_Connection_Error {
            get {
                return ResourceManager.GetString("Page3_AD_Connection_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection and authentication with the Active Directory server was successful..
        /// </summary>
        public static string Page3_AD_Connection_Success {
            get {
                return ResourceManager.GetString("Page3_AD_Connection_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to query:.
        /// </summary>
        public static string Page3_AD_Error {
            get {
                return ResourceManager.GetString("Page3_AD_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This should be in the format LDAP://mydc01.company.internal (it should be uppercase LDAP) where mydc01 is your domain controller and &apos;company&apos; and &apos;internal&apos; are the dns suffixes for your network. This can also be an IP address. You can usually get this information by running &quot;ipconfig&quot;..
        /// </summary>
        public static string Page3_AD_Group1_Label1 {
            get {
                return ResourceManager.GetString("Page3_AD_Group1_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string supports OU specifiers however doing it this way can cause issues. If you are unsure about this setting, it&apos;s recommended you download &lt;a href=&quot;http://technet.microsoft.com/en-us/sysinternals/bb963907&quot;&gt;AD Explorer&lt;/a&gt; first..
        /// </summary>
        public static string Page3_AD_Group1_Label2 {
            get {
                return ResourceManager.GetString("Page3_AD_Group1_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a username and password if the user that the app pool is running under does not have read access to Active Directory. This is useful if your domain is a separate forest from the main domain (i.e. another branch office)..
        /// </summary>
        public static string Page3_AD_Group1_Label3 {
            get {
                return ResourceManager.GetString("Page3_AD_Group1_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory LDAP connection string.
        /// </summary>
        public static string Page3_AD_Group1_Title {
            get {
                return ResourceManager.GetString("Page3_AD_Group1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Page3_AD_Group2_Label1 {
            get {
                return ResourceManager.GetString("Page3_AD_Group2_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Page3_AD_Group2_Label2 {
            get {
                return ResourceManager.GetString("Page3_AD_Group2_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the security group that users should belong to in order to be editors (people who can edit and create pages). The test button uses the connection settings entered above. .
        /// </summary>
        public static string Page3_AD_Group3_Label {
            get {
                return ResourceManager.GetString("Page3_AD_Group3_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor group name.
        /// </summary>
        public static string Page3_AD_Group3_Title {
            get {
                return ResourceManager.GetString("Page3_AD_Group3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the security group that users should belong to in order to be admins. Admins have the same rights as editors, but also have access to configuration settings and tools for the site.The test button uses the connection settings entered above..
        /// </summary>
        public static string Page3_AD_Group4_Label {
            get {
                return ResourceManager.GetString("Page3_AD_Group4_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin group name.
        /// </summary>
        public static string Page3_AD_Group4_Title {
            get {
                return ResourceManager.GetString("Page3_AD_Group4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The group was queried sucessfully..
        /// </summary>
        public static string Page3_AD_Success {
            get {
                return ResourceManager.GetString("Page3_AD_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the editor role - people who can edit and create pages..
        /// </summary>
        public static string Page3_DB_Group1_Label1 {
            get {
                return ResourceManager.GetString("Page3_DB_Group1_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor role name.
        /// </summary>
        public static string Page3_DB_Group1_Title {
            get {
                return ResourceManager.GetString("Page3_DB_Group1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the admin role. Admins have the same rights as editors, but also have access to configuration settings and tools for the site..
        /// </summary>
        public static string Page3_DB_Group2_Label1 {
            get {
                return ResourceManager.GetString("Page3_DB_Group2_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin role name.
        /// </summary>
        public static string Page3_DB_Group2_Title {
            get {
                return ResourceManager.GetString("Page3_DB_Group2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option if you want to allow people to signup as a new users. If left unchecked, only admins will be able to create new users. .
        /// </summary>
        public static string Page3_DB_Group3_Label1 {
            get {
                return ResourceManager.GetString("Page3_DB_Group3_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow new user signups. .
        /// </summary>
        public static string Page3_DB_Group3_Label2 {
            get {
                return ResourceManager.GetString("Page3_DB_Group3_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user signups.
        /// </summary>
        public static string Page3_DB_Group3_Title {
            get {
                return ResourceManager.GetString("Page3_DB_Group3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are allowing user signups, it&apos;s recommended that you also enable Recaptcha support. This is a free anti-spam bot service provided by Google, you will need to signup and copy your public and private key into the fields below. &lt;a href=&quot;https://www.google.com/recaptcha/admin/create&quot; target=&quot;_blank&quot;&gt;Signup here&lt;/a&gt; - you will need to create a google account first..
        /// </summary>
        public static string Page3_DB_Group4_Label1 {
            get {
                return ResourceManager.GetString("Page3_DB_Group4_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Recaptcha anti-spam service. .
        /// </summary>
        public static string Page3_DB_Group4_Label2 {
            get {
                return ResourceManager.GetString("Page3_DB_Group4_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key.
        /// </summary>
        public static string Page3_DB_Group4_Label3 {
            get {
                return ResourceManager.GetString("Page3_DB_Group4_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private key.
        /// </summary>
        public static string Page3_DB_Group4_Label4 {
            get {
                return ResourceManager.GetString("Page3_DB_Group4_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Recaptcha.
        /// </summary>
        public static string Page3_DB_Group4_Title {
            get {
                return ResourceManager.GetString("Page3_DB_Group4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the email address for the admin user. You can add more admins in the settings page, so this user does not &apos;own&apos; the site.
        /// </summary>
        public static string Page3_DB_Group5_Label1 {
            get {
                return ResourceManager.GetString("Page3_DB_Group5_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin email.
        /// </summary>
        public static string Page3_DB_Group5_Title {
            get {
                return ResourceManager.GetString("Page3_DB_Group5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the password for the admin user..
        /// </summary>
        public static string Page3_DB_Group6_Label1 {
            get {
                return ResourceManager.GetString("Page3_DB_Group6_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin password.
        /// </summary>
        public static string Page3_DB_Group6_Title {
            get {
                return ResourceManager.GetString("Page3_DB_Group6_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All passwords are one-way encrypted using SHA128 and a salt. This means passwords are not recoverable and will require and admin to reset them (there is no reset password functionality yet). The minimum password length is 6 characters..
        /// </summary>
        public static string Page3_DB_Label {
            get {
                return ResourceManager.GetString("Page3_DB_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use windows authentication.
        /// </summary>
        public static string Page3_Group1_Label {
            get {
                return ResourceManager.GetString("Page3_Group1_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows authentication.
        /// </summary>
        public static string Page3_Group1_Title {
            get {
                return ResourceManager.GetString("Page3_Group1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to users to be authenticated against an Active Directory using Windows authentication?.
        /// </summary>
        public static string Page3_Label1 {
            get {
                return ResourceManager.GetString("Page3_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to write to the folder:.
        /// </summary>
        public static string Page4_Group1_Error {
            get {
                return ResourceManager.GetString("Page4_Group1_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the directory where all files are uploaded to. This directory will need write permission by the user that the app pool runs under. Most of the time you shouldn&apos;t have to worry about changing the permissions for the folder, as they will be inherited from the parent folder. .
        /// </summary>
        public static string Page4_Group1_Label1 {
            get {
                return ResourceManager.GetString("Page4_Group1_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure the folder path begins with &quot;~/&quot; for the website root. You should check the folder can be accessed by the browser as well as the being writeable to, as folders such as App_Data and bin can be written to but will not show any images stored there. .
        /// </summary>
        public static string Page4_Group1_Label2 {
            get {
                return ResourceManager.GetString("Page4_Group1_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder exists and can be written to..
        /// </summary>
        public static string Page4_Group1_Success {
            get {
                return ResourceManager.GetString("Page4_Group1_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments folder.
        /// </summary>
        public static string Page4_Group1_Title {
            get {
                return ResourceManager.GetString("Page4_Group1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the file extensions that can be uploaded..
        /// </summary>
        public static string Page4_Group2_Label1 {
            get {
                return ResourceManager.GetString("Page4_Group2_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed extensions.
        /// </summary>
        public static string Page4_Group2_Title {
            get {
                return ResourceManager.GetString("Page4_Group2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the theme that the site uses. This should match a folder name in the Themes directory..
        /// </summary>
        public static string Page4_Group3_Label1 {
            get {
                return ResourceManager.GetString("Page4_Group3_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Page4_Group3_Title {
            get {
                return ResourceManager.GetString("Page4_Group3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the markup format that is used. Roadkill currently supports the following values: Creole, Markdown, Mediawiki..
        /// </summary>
        public static string Page4_Group4_Label1 {
            get {
                return ResourceManager.GetString("Page4_Group4_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creole is the recommended format. .
        /// </summary>
        public static string Page4_Group4_Label2 {
            get {
                return ResourceManager.GetString("Page4_Group4_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup type.
        /// </summary>
        public static string Page4_Group4_Title {
            get {
                return ResourceManager.GetString("Page4_Group4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Object caching.
        /// </summary>
        public static string Page4_Group5_Label1 {
            get {
                return ResourceManager.GetString("Page4_Group5_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roadkill caches all pages and content in memory after retrieving it from the database. The cache is automatically updated when a page changes. Recommended to increase the responsiveness of the site. Object caching is not currently supported for web gardens or web farms..
        /// </summary>
        public static string Page4_Group5_Label2 {
            get {
                return ResourceManager.GetString("Page4_Group5_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable browser cache.
        /// </summary>
        public static string Page4_Group5_Label3 {
            get {
                return ResourceManager.GetString("Page4_Group5_Label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will tell the browser to cache Roadkill pages, and check for updates (If-Modified-Since) each time the page is loaded. If no update is found, no content is returned from the server. Recommended to increase the responsiveness of the site..
        /// </summary>
        public static string Page4_Group5_Label4 {
            get {
                return ResourceManager.GetString("Page4_Group5_Label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Now unused, can be removed in 2.0).
        /// </summary>
        public static string Page4_Group5_Label5 {
            get {
                return ResourceManager.GetString("Page4_Group5_Label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        public static string Page4_Group5_Title {
            get {
                return ResourceManager.GetString("Page4_Group5_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost done...Finally some extra tweakable settings. .
        /// </summary>
        public static string Page4_Label1 {
            get {
                return ResourceManager.GetString("Page4_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go back through the installation steps and check your settings. The error message was:.
        /// </summary>
        public static string Page5_Error_Label1 {
            get {
                return ResourceManager.GetString("Page5_Error_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the install.
        /// </summary>
        public static string Page5_Error_Title {
            get {
                return ResourceManager.GetString("Page5_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you are using IIS7+ you may need to configure the web.config file for your security setup, below are the elements that are required.If you receive 500 errors after making these changes, then the section is locked at a parent level, and you will need to make thechanges via the IIS manager..
        /// </summary>
        public static string Page5_Success_AD_Label {
            get {
                return ResourceManager.GetString("Page5_Success_AD_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Authentication - please read.
        /// </summary>
        public static string Page5_Success_AD_Title {
            get {
                return ResourceManager.GetString("Page5_Success_AD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to the site.
        /// </summary>
        public static string Page5_Success_Label1 {
            get {
                return ResourceManager.GetString("Page5_Success_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation successful.
        /// </summary>
        public static string Page5_Success_Title {
            get {
                return ResourceManager.GetString("Page5_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Shared_Back {
            get {
                return ResourceManager.GetString("Shared_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Shared_BackButton {
            get {
                return ResourceManager.GetString("Shared_BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string Shared_Continue {
            get {
                return ResourceManager.GetString("Shared_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure!.
        /// </summary>
        public static string Shared_Failure {
            get {
                return ResourceManager.GetString("Shared_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Shared_NextButton {
            get {
                return ResourceManager.GetString("Shared_NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Shared_Stage1 {
            get {
                return ResourceManager.GetString("Shared_Stage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Shared_Stage2 {
            get {
                return ResourceManager.GetString("Shared_Stage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string Shared_Stage3 {
            get {
                return ResourceManager.GetString("Shared_Stage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extras.
        /// </summary>
        public static string Shared_Stage4 {
            get {
                return ResourceManager.GetString("Shared_Stage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string Shared_Stage5 {
            get {
                return ResourceManager.GetString("Shared_Stage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string Shared_Success {
            get {
                return ResourceManager.GetString("Shared_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test.
        /// </summary>
        public static string Shared_TestButton {
            get {
                return ResourceManager.GetString("Shared_TestButton", resourceCulture);
            }
        }
    }
}
