//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Core.Localization.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roadkill.Core.Localization.Resx.SiteStrings", typeof(SiteStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem activating your account. It may have already been activated..
        /// </summary>
        public static string Activate_Error {
            get {
                return ResourceManager.GetString("Activate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation was unsuccessful.
        /// </summary>
        public static string Activate_Error_Title {
            get {
                return ResourceManager.GetString("Activate_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been sucessfully activated..
        /// </summary>
        public static string Activate_Label {
            get {
                return ResourceManager.GetString("Activate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to login.
        /// </summary>
        public static string Activate_Link {
            get {
                return ResourceManager.GetString("Activate_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation successful.
        /// </summary>
        public static string Activate_Success_Title {
            get {
                return ResourceManager.GetString("Activate_Success_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Activation.
        /// </summary>
        public static string Activate_Title {
            get {
                return ResourceManager.GetString("Activate_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages found..
        /// </summary>
        public static string AllPages_NoPages {
            get {
                return ResourceManager.GetString("AllPages_NoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pages.
        /// </summary>
        public static string AllPages_Title {
            get {
                return ResourceManager.GetString("AllPages_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AllPages_TitleColumnHeading {
            get {
                return ResourceManager.GetString("AllPages_TitleColumnHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags found..
        /// </summary>
        public static string AllTags_NoResults {
            get {
                return ResourceManager.GetString("AllTags_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tags.
        /// </summary>
        public static string AllTags_Title {
            get {
                return ResourceManager.GetString("AllTags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Button_Preview {
            get {
                return ResourceManager.GetString("Button_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page can only be edited by administrators..
        /// </summary>
        public static string EditPage_AdminOnly {
            get {
                return ResourceManager.GetString("EditPage_AdminOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the page:.
        /// </summary>
        public static string EditPage_Error {
            get {
                return ResourceManager.GetString("EditPage_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image title.
        /// </summary>
        public static string EditPage_Image_Title {
            get {
                return ResourceManager.GetString("EditPage_Image_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link text.
        /// </summary>
        public static string EditPage_LinkText_PlaceHolder {
            get {
                return ResourceManager.GetString("EditPage_LinkText_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter url or page name.
        /// </summary>
        public static string EditPage_LinkUrl_PlaceHolder {
            get {
                return ResourceManager.GetString("EditPage_LinkUrl_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string EditPage_Preview {
            get {
                return ResourceManager.GetString("EditPage_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string EditPage_Tags_Label {
            get {
                return ResourceManager.GetString("EditPage_Tags_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/edit page.
        /// </summary>
        public static string EditPage_Title {
            get {
                return ResourceManager.GetString("EditPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string EditPage_Title_Label {
            get {
                return ResourceManager.GetString("EditPage_Title_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Bold text markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Bold {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Bullet List markup characters..
        /// </summary>
        public static string EditPage_Toolbar_BulletList {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_BulletList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Heading 1 level markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Heading1 {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Heading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Heading 1 level markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Heading2 {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Heading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Heading 1 level markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Heading3 {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Heading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Heading 4 level markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Heading4 {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Heading4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Heading 5 level markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Heading5 {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Heading5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Help reference for the markup syntax..
        /// </summary>
        public static string EditPage_Toolbar_Help {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Image {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Italic markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Italic {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert URL Link markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Link {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Numbered List markup characters..
        /// </summary>
        public static string EditPage_Toolbar_NumberList {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_NumberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Underline markup characters..
        /// </summary>
        public static string EditPage_Toolbar_Underline {
            get {
                return ResourceManager.GetString("EditPage_Toolbar_Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string FileExplorer_Button_Create {
            get {
                return ResourceManager.GetString("FileExplorer_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string FileExplorer_Button_Select {
            get {
                return ResourceManager.GetString("FileExplorer_Button_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string FileExplorer_Button_Upload {
            get {
                return ResourceManager.GetString("FileExplorer_Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file.
        /// </summary>
        public static string FileExplorer_ChooseFile {
            get {
                return ResourceManager.GetString("FileExplorer_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with the extension &apos;{0}&apos; are not allowed to be uploaded.
        /// </summary>
        public static string FileExplorer_Error_BadExtension {
            get {
                return ResourceManager.GetString("FileExplorer_Error_BadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred deleting the file: {0}.
        /// </summary>
        public static string FileExplorer_Error_DeleteFile {
            get {
                return ResourceManager.GetString("FileExplorer_Error_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred uploading the file: {0}.
        /// </summary>
        public static string FileExplorer_Error_FileUpload {
            get {
                return ResourceManager.GetString("FileExplorer_Error_FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating the directory: {0}.
        /// </summary>
        public static string FileExplorer_Error_NewDirectory {
            get {
                return ResourceManager.GetString("FileExplorer_Error_NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder name:.
        /// </summary>
        public static string FileExplorer_FolderName {
            get {
                return ResourceManager.GetString("FileExplorer_FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory.
        /// </summary>
        public static string FileExplorer_NewDirectory {
            get {
                return ResourceManager.GetString("FileExplorer_NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File explorer.
        /// </summary>
        public static string FileExplorer_Title {
            get {
                return ResourceManager.GetString("FileExplorer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a file.
        /// </summary>
        public static string FileExplorer_Upload {
            get {
                return ResourceManager.GetString("FileExplorer_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited by.
        /// </summary>
        public static string History_EditedBy {
            get {
                return ResourceManager.GetString("History_EditedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited on.
        /// </summary>
        public static string History_EditedOn {
            get {
                return ResourceManager.GetString("History_EditedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert.
        /// </summary>
        public static string History_RevertLink {
            get {
                return ResourceManager.GetString("History_RevertLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page history.
        /// </summary>
        public static string History_Title {
            get {
                return ResourceManager.GetString("History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string History_Version {
            get {
                return ResourceManager.GetString("History_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username/password is incorrect.
        /// </summary>
        public static string Login_Error {
            get {
                return ResourceManager.GetString("Login_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten your password?.
        /// </summary>
        public static string Login_ForgottenPassword {
            get {
                return ResourceManager.GetString("Login_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was unsuccessful.
        /// </summary>
        public static string Login_Unsuccessful_Title {
            get {
                return ResourceManager.GetString("Login_Unsuccessful_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages.
        /// </summary>
        public static string Navigation_AllPages {
            get {
                return ResourceManager.GetString("Navigation_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Navigation_Categories {
            get {
                return ResourceManager.GetString("Navigation_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Navigation_Delete {
            get {
                return ResourceManager.GetString("Navigation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Navigation_Edit {
            get {
                return ResourceManager.GetString("Navigation_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Navigation_History {
            get {
                return ResourceManager.GetString("Navigation_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Navigation_Login {
            get {
                return ResourceManager.GetString("Navigation_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Navigation_Logout {
            get {
                return ResourceManager.GetString("Navigation_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string Navigation_MainPage {
            get {
                return ResourceManager.GetString("Navigation_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        public static string Navigation_NewPage {
            get {
                return ResourceManager.GetString("Navigation_NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Navigation_Register {
            get {
                return ResourceManager.GetString("Navigation_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site settings.
        /// </summary>
        public static string Navigation_SiteSettings {
            get {
                return ResourceManager.GetString("Navigation_SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        public static string Navigation_ViewHistory {
            get {
                return ResourceManager.GetString("Navigation_ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set a main page, create a page and assign the tag &apos;homepage&apos; to it. .
        /// </summary>
        public static string NoMainPage_Label {
            get {
                return ResourceManager.GetString("NoMainPage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no mainpage set.
        /// </summary>
        public static string NoMainPage_Title {
            get {
                return ResourceManager.GetString("NoMainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string Page_Info_CreatedBy {
            get {
                return ResourceManager.GetString("Page_Info_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created on:.
        /// </summary>
        public static string Page_Info_CreatedOn {
            get {
                return ResourceManager.GetString("Page_Info_CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified by:.
        /// </summary>
        public static string Page_Info_ModifiedBy {
            get {
                return ResourceManager.GetString("Page_Info_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last modified on:.
        /// </summary>
        public static string Page_Info_ModifiedOn {
            get {
                return ResourceManager.GetString("Page_Info_ModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The title field is required..
        /// </summary>
        public static string Page_Validation_Title {
            get {
                return ResourceManager.GetString("Page_Validation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages for tag {0}.
        /// </summary>
        public static string Pages_ForTag {
            get {
                return ResourceManager.GetString("Pages_ForTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pages for {0}.
        /// </summary>
        public static string Pages_ForTag_NoPages {
            get {
                return ResourceManager.GetString("Pages_ForTag_NoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages created by {0}.
        /// </summary>
        public static string Pages_ForUser {
            get {
                return ResourceManager.GetString("Pages_ForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hasn&apos;t created any pages yet..
        /// </summary>
        public static string Pages_ForUser_NoPages {
            get {
                return ResourceManager.GetString("Pages_ForUser_NoPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred updating your profile.
        /// </summary>
        public static string Profile_Error {
            get {
                return ResourceManager.GetString("Profile_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword_Button {
            get {
                return ResourceManager.GetString("ResetPassword_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your new password..
        /// </summary>
        public static string ResetPassword_Complete_Label {
            get {
                return ResourceManager.GetString("ResetPassword_Complete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, an email has been sent to {0} with details on how to reset your password..
        /// </summary>
        public static string ResetPassword_EmailSent_Label {
            get {
                return ResourceManager.GetString("ResetPassword_EmailSent_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password reset request was sent..
        /// </summary>
        public static string ResetPassword_EmailSent_Title {
            get {
                return ResourceManager.GetString("ResetPassword_EmailSent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords do not match, or are too short.
        /// </summary>
        public static string ResetPassword_Error {
            get {
                return ResourceManager.GetString("ResetPassword_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address could not be found.
        /// </summary>
        public static string ResetPassword_Error_EmailNotFound {
            get {
                return ResourceManager.GetString("ResetPassword_Error_EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email address.
        /// </summary>
        public static string ResetPassword_Error_MissingEmail {
            get {
                return ResourceManager.GetString("ResetPassword_Error_MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset failed from a server error..
        /// </summary>
        public static string ResetPassword_Error_ServerError {
            get {
                return ResourceManager.GetString("ResetPassword_Error_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password reset key is no longer valid..
        /// </summary>
        public static string ResetPassword_Invalid_Label {
            get {
                return ResourceManager.GetString("ResetPassword_Invalid_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password invalid..
        /// </summary>
        public static string ResetPassword_Invalid_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Invalid_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email below to reset your password. You will then receive an email with a link to reset your password..
        /// </summary>
        public static string ResetPassword_Label {
            get {
                return ResourceManager.GetString("ResetPassword_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was sucessfully reset..
        /// </summary>
        public static string ResetPassword_Successful_Label {
            get {
                return ResourceManager.GetString("ResetPassword_Successful_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password successful..
        /// </summary>
        public static string ResetPassword_Successful_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Successful_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset your password..
        /// </summary>
        public static string ResetPassword_Title {
            get {
                return ResourceManager.GetString("ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search &apos;{0}&apos; did not match any pages.
        /// </summary>
        public static string Search_NoResults {
            get {
                return ResourceManager.GetString("Search_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search.
        /// </summary>
        public static string Search_PlaceHolder {
            get {
                return ResourceManager.GetString("Search_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results for &apos;{0}&apos;.
        /// </summary>
        public static string Search_Results {
            get {
                return ResourceManager.GetString("Search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Shared_ConfirmLink {
            get {
                return ResourceManager.GetString("Shared_ConfirmLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Shared_DeleteLink {
            get {
                return ResourceManager.GetString("Shared_DeleteLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Shared_EditLink {
            get {
                return ResourceManager.GetString("Shared_EditLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Shared_Email_Label {
            get {
                return ResourceManager.GetString("Shared_Email_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred:.
        /// </summary>
        public static string Shared_Error {
            get {
                return ResourceManager.GetString("Shared_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string Shared_Firstname {
            get {
                return ResourceManager.GetString("Shared_Firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page was last modified on.
        /// </summary>
        public static string Shared_LastModified {
            get {
                return ResourceManager.GetString("Shared_LastModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string Shared_Lastname {
            get {
                return ResourceManager.GetString("Shared_Lastname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as.
        /// </summary>
        public static string Shared_LoggedInAs {
            get {
                return ResourceManager.GetString("Shared_LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not logged in.
        /// </summary>
        public static string Shared_NotLoggedIn {
            get {
                return ResourceManager.GetString("Shared_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Shared_Password_Label {
            get {
                return ResourceManager.GetString("Shared_Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirm:.
        /// </summary>
        public static string Shared_PasswordConfirm_Label {
            get {
                return ResourceManager.GetString("Shared_PasswordConfirm_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by Roadkill Wiki.
        /// </summary>
        public static string Shared_PoweredBy {
            get {
                return ResourceManager.GetString("Shared_PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        public static string Shared_Username {
            get {
                return ResourceManager.GetString("Shared_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        public static string Signup_Button {
            get {
                return ResourceManager.GetString("Signup_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend email confirmation.
        /// </summary>
        public static string Signup_Complete_EmailResend_Button {
            get {
                return ResourceManager.GetString("Signup_Complete_EmailResend_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The confirmation email was resent..
        /// </summary>
        public static string Signup_Complete_EmailResent {
            get {
                return ResourceManager.GetString("Signup_Complete_EmailResent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, an email has been sent to {0} with details on how to complete the signup..
        /// </summary>
        public static string Signup_Complete_Label {
            get {
                return ResourceManager.GetString("Signup_Complete_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not received your email?.
        /// </summary>
        public static string Signup_Complete_NoEmail {
            get {
                return ResourceManager.GetString("Signup_Complete_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signup complete..
        /// </summary>
        public static string Signup_Complete_Title {
            get {
                return ResourceManager.GetString("Signup_Complete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred with the signup..
        /// </summary>
        public static string Signup_Error_General {
            get {
                return ResourceManager.GetString("Signup_Error_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two words for the anti-spam box were incorrect.
        /// </summary>
        public static string Signup_Error_Recaptcha {
            get {
                return ResourceManager.GetString("Signup_Error_Recaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter you details below..
        /// </summary>
        public static string Signup_Label {
            get {
                return ResourceManager.GetString("Signup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register / Signup.
        /// </summary>
        public static string Signup_Title {
            get {
                return ResourceManager.GetString("Signup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string SiteSettings_Configuration {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication/LDAP connection string.
        /// </summary>
        public static string SiteSettings_Configuration_AD_Connection {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP connection string for the Active Directory connection.This should be in the format LDAP://mydc01.company.internal (it should be uppercase LDAP)..
        /// </summary>
        public static string SiteSettings_Configuration_AD_Connection_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Connection_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP password.
        /// </summary>
        public static string SiteSettings_Configuration_AD_Password {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password to use for authentication..
        /// </summary>
        public static string SiteSettings_Configuration_AD_Password_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Password_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP username.
        /// </summary>
        public static string SiteSettings_Configuration_AD_Username {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username to authenticate against the Active Directory with. Leave blank if the app pool is running under a user with this permission..
        /// </summary>
        public static string SiteSettings_Configuration_AD_Username_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Username_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin role/security group name.
        /// </summary>
        public static string SiteSettings_Configuration_AdminRole {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;WARNING&lt;/b&gt; changing this may lock you out of the site when using Active Directory/Windows authentication. Make a backup of your web.config first before saving. &lt;br/&gt;&lt;br/&gt;This is the name of the admin role. Admins have the same rights as editors, but also have access to configuration settings and tools for the site..
        /// </summary>
        public static string SiteSettings_Configuration_AdminRole_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AdminRole_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user signups.
        /// </summary>
        public static string SiteSettings_Configuration_AllowUserSignups {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AllowUserSignups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option if you want to allow people to signup as a new users..
        /// </summary>
        public static string SiteSettings_Configuration_AllowUserSignups_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AllowUserSignups_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments folder.
        /// </summary>
        public static string SiteSettings_Configuration_Attachments {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the directory where all files are uploaded to. This setting should start with ~/ to indicate the site root folder..
        /// </summary>
        public static string SiteSettings_Configuration_Attachments_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Attachments_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache page text.
        /// </summary>
        public static string SiteSettings_Configuration_CachePageText {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_CachePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache text content. Unchecking this will mean each page&apos;s textual content is loaded from the database each time..
        /// </summary>
        public static string SiteSettings_Configuration_CachePageText_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_CachePageText_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching.
        /// </summary>
        public static string SiteSettings_Configuration_Caching {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Caching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable NHibernate caching. Roadkill uses NHibernate caching along with ASP.NET&apos;s output caching. It&apos;s recommended that you enable caching to increase the responsiveness of the site. Database caching is not currently supported for for web gardens or web farms..
        /// </summary>
        public static string SiteSettings_Configuration_Caching_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Caching_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes your database type - you will need to recreate the schema in the tools for this to work correctly..
        /// </summary>
        public static string SiteSettings_Configuration_ConnectionStrings_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_ConnectionStrings_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string SiteSettings_Configuration_Database {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection string.
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseConnectionString {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection string..
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseConnectionString_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseConnectionString_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type.
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseType {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes your database type - you will need to recreate the schema in the tools for this to work correctly..
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseType_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseType_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor role/security group name.
        /// </summary>
        public static string SiteSettings_Configuration_EditorRole {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EditorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the editor role - people who can edit and create pages. This is only used for Active Directory/Windows authentication - leave this blank to allow all users to be editors..
        /// </summary>
        public static string SiteSettings_Configuration_EditorRole_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EditorRole_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable recaptcha.
        /// </summary>
        public static string SiteSettings_Configuration_EnableRecaptcha {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EnableRecaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Recaptcha support - a free anti-spam bot service. You will need to signup and copy your public and private key into the fields below..
        /// </summary>
        public static string SiteSettings_Configuration_EnableRecaptcha_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EnableRecaptcha_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the settings.
        /// </summary>
        public static string SiteSettings_Configuration_Error {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed extensions.
        /// </summary>
        public static string SiteSettings_Configuration_Extensions {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the file extensions that can be uploaded, comma separated..
        /// </summary>
        public static string SiteSettings_Configuration_Extensions_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Extensions_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string SiteSettings_Configuration_General {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup type.
        /// </summary>
        public static string SiteSettings_Configuration_MarkupType {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_MarkupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the markup format that is used. Roadkill currently supports the following values: Creole, Markdown, Mediawiki..
        /// </summary>
        public static string SiteSettings_Configuration_MarkupType_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_MarkupType_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha private key.
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPrivateKey {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key for Recaptcha, which is provided when you signup with recaptcha..
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPrivateKey_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPrivateKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha public key.
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPublicKey {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public key for Recaptcha, which is provided when you signup with recaptcha..
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPublicKey_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPublicKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string SiteSettings_Configuration_Security {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        public static string SiteSettings_Configuration_Site {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string SiteSettings_Configuration_SiteName {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the site, which is used in certain themes..
        /// </summary>
        public static string SiteSettings_Configuration_SiteName_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site url.
        /// </summary>
        public static string SiteSettings_Configuration_SiteUrl {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url of the site, which is used in signup and reset password emails.  Do not include the trailing slash..
        /// </summary>
        public static string SiteSettings_Configuration_SiteUrl_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteUrl_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SiteSettings_Configuration_Theme {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the theme that the site uses. This should match a folder name in the Themes directory..
        /// </summary>
        public static string SiteSettings_Configuration_Theme_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Theme_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Settings.
        /// </summary>
        public static string SiteSettings_Configuration_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Authentication.
        /// </summary>
        public static string SiteSettings_Configuration_UseWindowsAuth {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_UseWindowsAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;WARNING&lt;/b&gt; changing this may lock you out of the site. Make a backup of your web.config first before saving.&lt;br/&gt;&lt;br/&gt; Sets whether to use Windows Authentication and Active Directory for authentication..
        /// </summary>
        public static string SiteSettings_Configuration_UseWindowsAuth_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_UseWindowsAuth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string SiteSettings_Tools {
            get {
                return ResourceManager.GetString("SiteSettings_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the database.
        /// </summary>
        public static string SiteSettings_Tools_ClearDatabase {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ClearDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears all pages and text from the database. This does not remove any users..
        /// </summary>
        public static string SiteSettings_Tools_ClearDatabase_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ClearDatabase_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database cleared.
        /// </summary>
        public static string SiteSettings_Tools_ClearDatabase_Message {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ClearDatabase_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export attachments as a zip.
        /// </summary>
        public static string SiteSettings_Tools_ExportAttachments {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting attachments failed: {0}.
        /// </summary>
        public static string SiteSettings_Tools_ExportAttachments_Error {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportAttachments_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all the contents of attachments folder and subfolders as a zip file..
        /// </summary>
        public static string SiteSettings_Tools_ExportAttachments_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportAttachments_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all content as a zip.
        /// </summary>
        public static string SiteSettings_Tools_ExportContent {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wiki content export failed: {0}.
        /// </summary>
        public static string SiteSettings_Tools_ExportContent_Error {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportContent_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all pages, including text content as a series of &quot;.wiki&quot; files. Only the current content and tags are included, no history is provided. This zip file does not include the attachments folder..
        /// </summary>
        public static string SiteSettings_Tools_ExportContent_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportContent_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XML.
        /// </summary>
        public static string SiteSettings_Tools_ExportXml {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting to XML failed: {0}.
        /// </summary>
        public static string SiteSettings_Tools_ExportXml_Error {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportXml_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all page text content and all history as a single XML file..
        /// </summary>
        public static string SiteSettings_Tools_ExportXml_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportXml_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild search index.
        /// </summary>
        public static string SiteSettings_Tools_RebuildSearch {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RebuildSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces a re-build of the page search index, useful if the search begins to get out of sync for any reason..
        /// </summary>
        public static string SiteSettings_Tools_RebuildSearch_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RebuildSearch_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild of search index complete.
        /// </summary>
        public static string SiteSettings_Tools_RebuildSearch_Message {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RebuildSearch_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a tag.
        /// </summary>
        public static string SiteSettings_Tools_RenameTag {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing tag:.
        /// </summary>
        public static string SiteSettings_Tools_RenameTag_Existing {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag_Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will rename a tag, and update all pages that reference the tag to use the new tagname. The tagname is case sensitive..
        /// </summary>
        public static string SiteSettings_Tools_RenameTag_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag rename successful.
        /// </summary>
        public static string SiteSettings_Tools_RenameTag_Message {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag name:.
        /// </summary>
        public static string SiteSettings_Tools_RenameTag_New {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from screwturn.
        /// </summary>
        public static string SiteSettings_Tools_ScrewTurnImport {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ScrewTurnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screwturn connection string:.
        /// </summary>
        public static string SiteSettings_Tools_ScrewTurnImport_Connection {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ScrewTurnImport_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports all content from a Screwturn 2 database. You will need to set the markuptype to MediaWiki in the settings/web.config file for the format to be compatible. As screwturn uses as variation on the mediawiki syntax, some content will not render perfectly. This includes some images and links..
        /// </summary>
        public static string SiteSettings_Tools_ScrewTurnImport_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ScrewTurnImport_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import successful.
        /// </summary>
        public static string SiteSettings_Tools_ScrewTurnImport_Message {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ScrewTurnImport_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site tools.
        /// </summary>
        public static string SiteSettings_Tools_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string SiteSettings_Users {
            get {
                return ResourceManager.GetString("SiteSettings_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User names and passwords are not editable with Windows authentication - you should do this through Active Directory..
        /// </summary>
        public static string SiteSettings_Users_AD_Label1 {
            get {
                return ResourceManager.GetString("SiteSettings_Users_AD_Label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a user as an admin or editor, make sure they are part of the Windows security group that you have specified for the &quot;AdminRolename&quot; and &quot;EditorRolename&quot; settings in the web.config..
        /// </summary>
        public static string SiteSettings_Users_AD_Label2 {
            get {
                return ResourceManager.GetString("SiteSettings_Users_AD_Label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows/Active Directory authentication is enabled.
        /// </summary>
        public static string SiteSettings_Users_AD_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Users_AD_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add admin.
        /// </summary>
        public static string SiteSettings_Users_AddAdminDialog_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Users_AddAdminDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add editor.
        /// </summary>
        public static string SiteSettings_Users_AddEditorDialog_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Users_AddEditorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the user details:.
        /// </summary>
        public static string SiteSettings_Users_AddUserDialog_Error {
            get {
                return ResourceManager.GetString("SiteSettings_Users_AddUserDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For existing users, leave the password fields blank to change just the username..
        /// </summary>
        public static string SiteSettings_Users_AddUserDialog_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Users_AddUserDialog_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string SiteSettings_Users_Admins {
            get {
                return ResourceManager.GetString("SiteSettings_Users_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SiteSettings_Users_ColumnHeader_Email {
            get {
                return ResourceManager.GetString("SiteSettings_Users_ColumnHeader_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SiteSettings_Users_ColumnHeader_Username {
            get {
                return ResourceManager.GetString("SiteSettings_Users_ColumnHeader_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string SiteSettings_Users_Editors {
            get {
                return ResourceManager.GetString("SiteSettings_Users_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating the user failed..
        /// </summary>
        public static string SiteSettings_Users_EditUser_Error {
            get {
                return ResourceManager.GetString("SiteSettings_Users_EditUser_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit user.
        /// </summary>
        public static string SiteSettings_Users_EditUserDialog_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Users_EditUserDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New admin user.
        /// </summary>
        public static string SiteSettings_Users_NewAdmin {
            get {
                return ResourceManager.GetString("SiteSettings_Users_NewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New editor user.
        /// </summary>
        public static string SiteSettings_Users_NewEditor {
            get {
                return ResourceManager.GetString("SiteSettings_Users_NewEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site users.
        /// </summary>
        public static string SiteSettings_Users_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Users_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attachments folder is empty..
        /// </summary>
        public static string SiteSettings_Validation_AttachmentsEmpty {
            get {
                return ResourceManager.GetString("SiteSettings_Validation_AttachmentsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string is empty..
        /// </summary>
        public static string SiteSettings_Validation_ConnectionEmpty {
            get {
                return ResourceManager.GetString("SiteSettings_Validation_ConnectionEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The markup type is empty..
        /// </summary>
        public static string SiteSettings_Validation_MarkupTypeEmpty {
            get {
                return ResourceManager.GetString("SiteSettings_Validation_MarkupTypeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sitename is empty..
        /// </summary>
        public static string SiteSettings_Validation_SiteNameEmpty {
            get {
                return ResourceManager.GetString("SiteSettings_Validation_SiteNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site url is empty..
        /// </summary>
        public static string SiteSettings_Validation_SiteUrlEmpty {
            get {
                return ResourceManager.GetString("SiteSettings_Validation_SiteUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The theme is empty..
        /// </summary>
        public static string SiteSettings_Validation_ThemeEmpty {
            get {
                return ResourceManager.GetString("SiteSettings_Validation_ThemeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field is required..
        /// </summary>
        public static string User_Validation_Email {
            get {
                return ResourceManager.GetString("User_Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email field does not contain a valid email..
        /// </summary>
        public static string User_Validation_Email_Check {
            get {
                return ResourceManager.GetString("User_Validation_Email_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email {0} already exists..
        /// </summary>
        public static string User_Validation_EmailExists {
            get {
                return ResourceManager.GetString("User_Validation_EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The passwords don&apos;t match..
        /// </summary>
        public static string User_Validation_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("User_Validation_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password is less than {0} characters.
        /// </summary>
        public static string User_Validation_PasswordTooShort {
            get {
                return ResourceManager.GetString("User_Validation_PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username field is required..
        /// </summary>
        public static string User_Validation_Username {
            get {
                return ResourceManager.GetString("User_Validation_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The The username is empty..
        /// </summary>
        public static string User_Validation_UsernameEmpty {
            get {
                return ResourceManager.GetString("User_Validation_UsernameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username {0} already exists..
        /// </summary>
        public static string User_Validation_UsernameExists {
            get {
                return ResourceManager.GetString("User_Validation_UsernameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back.
        /// </summary>
        public static string Version_BackLink {
            get {
                return ResourceManager.GetString("Version_BackLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string Version_Title {
            get {
                return ResourceManager.GetString("Version_Title", resourceCulture);
            }
        }
    }
}
