//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Roadkill.Site.App_GlobalResources.Resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Roadkill.Site.App_GlobalResources.Resx.SiteStrings", typeof(SiteStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Button_Import {
            get {
                return ResourceManager.GetString("Button_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Button_Login {
            get {
                return ResourceManager.GetString("Button_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Button_Preview {
            get {
                return ResourceManager.GetString("Button_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string Button_Rename {
            get {
                return ResourceManager.GetString("Button_Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Button_Upload {
            get {
                return ResourceManager.GetString("Button_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page can only be edited by administrators..
        /// </summary>
        public static string CreatePage_AdminOnly {
            get {
                return ResourceManager.GetString("CreatePage_AdminOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a file.
        /// </summary>
        public static string CreatePage_ChooseFile {
            get {
                return ResourceManager.GetString("CreatePage_ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enter url or page name|Link text.
        /// </summary>
        public static string CreatePage_Link_PlaceHolder {
            get {
                return ResourceManager.GetString("CreatePage_Link.PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New directory.
        /// </summary>
        public static string CreatePage_NewDirectory {
            get {
                return ResourceManager.GetString("CreatePage_NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string CreatePage_RequiredField {
            get {
                return ResourceManager.GetString("CreatePage_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string CreatePage_Tags {
            get {
                return ResourceManager.GetString("CreatePage_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string CreatePage_Title {
            get {
                return ResourceManager.GetString("CreatePage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload a file.
        /// </summary>
        public static string CreatePage_UploadFile {
            get {
                return ResourceManager.GetString("CreatePage_UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Login_Email {
            get {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgotten your password?.
        /// </summary>
        public static string Login_ForgottenPassword {
            get {
                return ResourceManager.GetString("Login_ForgottenPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All pages.
        /// </summary>
        public static string Navigation_All_pages {
            get {
                return ResourceManager.GetString("Navigation_All pages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Navigation_Categories {
            get {
                return ResourceManager.GetString("Navigation_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Navigation_Delete {
            get {
                return ResourceManager.GetString("Navigation_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Navigation_Edit {
            get {
                return ResourceManager.GetString("Navigation_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Navigation_History {
            get {
                return ResourceManager.GetString("Navigation_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as .
        /// </summary>
        public static string Navigation_LoggedInAs {
            get {
                return ResourceManager.GetString("Navigation_LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Navigation_Login {
            get {
                return ResourceManager.GetString("Navigation_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Navigation_Logout {
            get {
                return ResourceManager.GetString("Navigation_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string Navigation_MainPage {
            get {
                return ResourceManager.GetString("Navigation_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New page.
        /// </summary>
        public static string Navigation_NewPage {
            get {
                return ResourceManager.GetString("Navigation_NewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site settings.
        /// </summary>
        public static string Navigation_SiteSettings {
            get {
                return ResourceManager.GetString("Navigation_SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        public static string Navigation_ViewHistory {
            get {
                return ResourceManager.GetString("Navigation_ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To set a main page, create a page and assign the tag &apos;homepage&apos; to it. .
        /// </summary>
        public static string NoMainPage_Label {
            get {
                return ResourceManager.GetString("NoMainPage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no mainpage set.
        /// </summary>
        public static string NoMainPage_Title {
            get {
                return ResourceManager.GetString("NoMainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add/edit page.
        /// </summary>
        public static string Page_AddEditPage {
            get {
                return ResourceManager.GetString("Page_AddEditPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Pages.
        /// </summary>
        public static string Page_AllPages {
            get {
                return ResourceManager.GetString("Page_AllPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Tags.
        /// </summary>
        public static string Page_AllTags {
            get {
                return ResourceManager.GetString("Page_AllTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search &apos;{0}&apos; did not match any pages.
        /// </summary>
        public static string Search_NoResults {
            get {
                return ResourceManager.GetString("Search_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to search.
        /// </summary>
        public static string Search_PlaceHolder {
            get {
                return ResourceManager.GetString("Search_PlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results for &apos;{0}&apos;.
        /// </summary>
        public static string Search_Results {
            get {
                return ResourceManager.GetString("Search_Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add admin.
        /// </summary>
        public static string SiteSettings_AddAdminDialog_Title {
            get {
                return ResourceManager.GetString("SiteSettings_AddAdminDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add editor.
        /// </summary>
        public static string SiteSettings_AddEditorDialog_Title {
            get {
                return ResourceManager.GetString("SiteSettings_AddEditorDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the user details.
        /// </summary>
        public static string SiteSettings_AddUserDialog_Error {
            get {
                return ResourceManager.GetString("SiteSettings_AddUserDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For existing users, leave the password fields blank to change just the username..
        /// </summary>
        public static string SiteSettings_AddUserDialog_Help {
            get {
                return ResourceManager.GetString("SiteSettings_AddUserDialog_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required.
        /// </summary>
        public static string SiteSettings_AddUserDialog_RequiredField {
            get {
                return ResourceManager.GetString("SiteSettings_AddUserDialog_RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admins.
        /// </summary>
        public static string SiteSettings_Admins {
            get {
                return ResourceManager.GetString("SiteSettings_Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string SiteSettings_Configuration {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication/LDAP connection string:.
        /// </summary>
        public static string SiteSettings_Configuration_AD_Connection {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The LDAP connection string for the Active Directory connection.This should be in the format LDAP://mydc01.company.internal (it should be uppercase LDAP)..
        /// </summary>
        public static string SiteSettings_Configuration_AD_Connection_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Connection_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP password:.
        /// </summary>
        public static string SiteSettings_Configuration_AD_Password {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password to use for authentication..
        /// </summary>
        public static string SiteSettings_Configuration_AD_Password_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Password_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP username:.
        /// </summary>
        public static string SiteSettings_Configuration_AD_Username {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username to authenticate against the Active Directory with. Leave blank if the app pool is running under a user with this permission..
        /// </summary>
        public static string SiteSettings_Configuration_AD_Username_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AD_Username_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin role/security group name.
        /// </summary>
        public static string SiteSettings_Configuration_AdminRole {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;WARNING&lt;/b&gt; changing this may lock you out of the site. Make a backup of your web.config first before saving. &lt;br/&gt;&lt;br/&gt;This is the name of the admin role. Admins have the same rights as editors, but also have access to configuration settings and tools for the site..
        /// </summary>
        public static string SiteSettings_Configuration_AdminRole_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AdminRole_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow user signups.
        /// </summary>
        public static string SiteSettings_Configuration_AllowUserSignups {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AllowUserSignups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option if you want to allow people to signup as a new users..
        /// </summary>
        public static string SiteSettings_Configuration_AllowUserSignups_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_AllowUserSignups_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments folder.
        /// </summary>
        public static string SiteSettings_Configuration_Attachments {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the directory where all files are uploaded to. This setting should start with ~/ to indicate the site root folder..
        /// </summary>
        public static string SiteSettings_Configuration_Attachments_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Attachments_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache page text.
        /// </summary>
        public static string SiteSettings_Configuration_CachePageText {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_CachePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache text content. Unchecking this will mean each page&apos;s textual content is loaded from the database each time..
        /// </summary>
        public static string SiteSettings_Configuration_CachePageText_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_CachePageText_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caching.
        /// </summary>
        public static string SiteSettings_Configuration_Caching {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Caching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable NHibernate caching. Roadkill uses NHibernate caching along with ASP.NET&apos;s output caching. It&apos;s recommended that you enable caching to increase the responsiveness of the site. Database caching is not currently supported for for web gardens or web farms..
        /// </summary>
        public static string SiteSettings_Configuration_Caching_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Caching_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection strings.
        /// </summary>
        public static string SiteSettings_Configuration_ConnectionStrings {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_ConnectionStrings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes your database type - you will need to recreate the schema in the tools for this to work correctly..
        /// </summary>
        public static string SiteSettings_Configuration_ConnectionStrings_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_ConnectionStrings_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database connection string.
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseConnectionString {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database connection string..
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseConnectionString_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseConnectionString_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database type.
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseType {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes your database type - you will need to recreate the schema in the tools for this to work correctly..
        /// </summary>
        public static string SiteSettings_Configuration_DatabaseType_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_DatabaseType_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor role/security group name.
        /// </summary>
        public static string SiteSettings_Configuration_EditorRole {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EditorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the name of the editor role - people who can edit and create pages..
        /// </summary>
        public static string SiteSettings_Configuration_EditorRole_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EditorRole_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable recaptcha.
        /// </summary>
        public static string SiteSettings_Configuration_EnableRecaptcha {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EnableRecaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Recaptcha support - a free anti-spam bot service. You will need to signup and copy your public and private key into the fields below..
        /// </summary>
        public static string SiteSettings_Configuration_EnableRecaptcha_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_EnableRecaptcha_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed extensions.
        /// </summary>
        public static string SiteSettings_Configuration_Extensions {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Extensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These are the file extensions that can be uploaded, comma separated..
        /// </summary>
        public static string SiteSettings_Configuration_Extensions_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Extensions_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markup type.
        /// </summary>
        public static string SiteSettings_Configuration_MarkupType {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_MarkupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the markup format that is used. Roadkill currently supports the following values: Creole, Markdown, Mediawiki..
        /// </summary>
        public static string SiteSettings_Configuration_MarkupType_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_MarkupType_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha private key.
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPrivateKey {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The private key for Recaptcha, which is provided when you signup with recaptcha..
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPrivateKey_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPrivateKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recaptcha public key.
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPublicKey {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public key for Recaptcha, which is provided when you signup with recaptcha..
        /// </summary>
        public static string SiteSettings_Configuration_RecaptchaPublicKey_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_RecaptchaPublicKey_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site name.
        /// </summary>
        public static string SiteSettings_Configuration_SiteName {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the site, which is used in certain themes..
        /// </summary>
        public static string SiteSettings_Configuration_SiteName_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteName_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site url.
        /// </summary>
        public static string SiteSettings_Configuration_SiteUrl {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url of the site, which is used in signup and reset password emails.  Do not include the trailing slash..
        /// </summary>
        public static string SiteSettings_Configuration_SiteUrl_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_SiteUrl_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string SiteSettings_Configuration_Theme {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the theme that the site uses. This should match a folder name in the Themes directory..
        /// </summary>
        public static string SiteSettings_Configuration_Theme_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_Theme_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Windows Authentication.
        /// </summary>
        public static string SiteSettings_Configuration_UseWindowsAuth {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_UseWindowsAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;WARNING&lt;/b&gt; changing this may lock you out of the site. Make a backup of your web.config first before saving.&lt;br/&gt;&lt;br/&gt; Sets whether to use Windows Authentication and Active Directory for authentication..
        /// </summary>
        public static string SiteSettings_Configuration_UseWindowsAuth_Help {
            get {
                return ResourceManager.GetString("SiteSettings_Configuration_UseWindowsAuth_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editors.
        /// </summary>
        public static string SiteSettings_Editors {
            get {
                return ResourceManager.GetString("SiteSettings_Editors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string SiteSettings_Email_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Email_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New admin user.
        /// </summary>
        public static string SiteSettings_NewAdmin {
            get {
                return ResourceManager.GetString("SiteSettings_NewAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New editor user.
        /// </summary>
        public static string SiteSettings_NewEditor {
            get {
                return ResourceManager.GetString("SiteSettings_NewEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string SiteSettings_Password_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Password_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password (confirm).
        /// </summary>
        public static string SiteSettings_PasswordConfirm_Title {
            get {
                return ResourceManager.GetString("SiteSettings_PasswordConfirm_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string SiteSettings_Tools {
            get {
                return ResourceManager.GetString("SiteSettings_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear the database.
        /// </summary>
        public static string SiteSettings_Tools_ClearDatabase {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ClearDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears all pages and text from the database. This does not remove any users. .
        /// </summary>
        public static string SiteSettings_Tools_ClearDatabase_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ClearDatabase.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export attachments as a zip.
        /// </summary>
        public static string SiteSettings_Tools_ExportAttachments {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all the contents of attachments folder and subfolders as a zip file. .
        /// </summary>
        public static string SiteSettings_Tools_ExportAttachments_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportAttachments.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export all content as a zip.
        /// </summary>
        public static string SiteSettings_Tools_ExportContent {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all pages, including text content as a series of &quot;.wiki&quot; files. Only the current content and tags are included, no history is provided. This zip file does not include the attachments folder. .
        /// </summary>
        public static string SiteSettings_Tools_ExportContent_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportContent.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XML.
        /// </summary>
        public static string SiteSettings_Tools_ExportXml {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports all page text content and all history as a single XML file. .
        /// </summary>
        public static string SiteSettings_Tools_ExportXml_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ExportXml.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebuild search index.
        /// </summary>
        public static string SiteSettings_Tools_RebuildSearch {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RebuildSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces a re-build of the page search index, useful if the search begins to get out of sync for any reason. .
        /// </summary>
        public static string SiteSettings_Tools_RebuildSearch_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RebuildSearch.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename a tag.
        /// </summary>
        public static string SiteSettings_Tools_RenameTag {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing tag.
        /// </summary>
        public static string SiteSettings_Tools_RenameTag_Existing {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag.Existing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will rename a tag, and update all pages that reference the tag to use the new tagname. The tagname is case sensitive..
        /// </summary>
        public static string SiteSettings_Tools_RenameTag_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag name.
        /// </summary>
        public static string SiteSettings_Tools_RenameTag_New {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_RenameTag.New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from screwturn.
        /// </summary>
        public static string SiteSettings_Tools_ScrewTurnImport {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ScrewTurnImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screwturn connection string:.
        /// </summary>
        public static string SiteSettings_Tools_ScrewTurnImport_Connection {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ScrewTurnImport.Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports all content from a Screwturn 2 database. You will need to set the markuptype to MediaWiki in the settings/web.config file for the format to be compatible. As screwturn uses as variation on the mediawiki syntax, some content will not render perfectly. This includes some images and links..
        /// </summary>
        public static string SiteSettings_Tools_ScrewTurnImport_Label {
            get {
                return ResourceManager.GetString("SiteSettings_Tools_ScrewTurnImport.Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string SiteSettings_Username_Title {
            get {
                return ResourceManager.GetString("SiteSettings_Username_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string SiteSettings_Users {
            get {
                return ResourceManager.GetString("SiteSettings_Users", resourceCulture);
            }
        }
    }
}
