declare var $;

//
// All variables below are declared in GlobalJSdeclare vars
//

declare var ROADKILL_CORESCRIPTPATH;
declare var ROADKILL_COREASSETPATH;
declare var ROADKILL_THEMEPATH;

// Edit page constants
declare var ROADKILL_TAGAJAXURL;
declare var ROADKILL_PREVIEWURL;
declare var ROADKILL_MARKUPTYPE;
declare var ROADKILL_WIKIMARKUPHELP;

// File manager constants
declare var ROADKILL_FILEMANAGERURL;
declare var ROADKILL_FILETREE_URL;
declare var ROADKILL_FILESELECTURL;
declare var ROADKILL_FILETREE_PATHNAME_URL;
declare var ROADKILL_ATTACHMENTSPATH;

// Tokens for the edit toolbar
declare var ROADKILL_EDIT_BOLD_TOKEN;
declare var ROADKILL_EDIT_ITALIC_TOKEN;
declare var ROADKILL_EDIT_UNDERLINE_TOKEN;
declare var ROADKILL_EDIT_LINK_STARTTOKEN;
declare var ROADKILL_EDIT_LINK_ENDTOKEN;
declare var ROADKILL_EDIT_IMAGE_STARTTOKEN;
declare var ROADKILL_EDIT_IMAGE_ENDTOKEN;
declare var ROADKILL_EDIT_NUMBERLIST_TOKEN;
declare var ROADKILL_EDIT_BULLETLIST_TOKEN;
declare var ROADKILL_EDIT_HEADING_TOKEN;
declare var ROADKILL_EDIT_LINK_URLPLACEHOLDER;
declare var ROADKILL_EDIT_LINK_TEXTPLACEHOLDER;
declare var ROADKILL_EDIT_IMAGE_TITLE;

declare var ROADKILL_ADDADMIN_FORMACTION;;
declare var ROADKILL_ADDEDITOR_FORMACTION;
declare var ROADKILL_EDITUSER_FORMACTION;

declare var ROADKILL_LINK_CONFIRM;
declare var ROADKILL_ADDADMIN_TITLE;
declare var ROADKILL_ADDEDITOR_TITLE;
declare var ROADKILL_EDITUSER_TITLE;

declare var ROADKILL_DELETE_CONFIRM;
declare var ROADKILL_DELETE_BASEFOLDER_ERROR;