<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Roadkill.Core</RootNamespace>
    <AssemblyName>Roadkill.Core</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591;CS1572;CS1573;CS1574;CS1570;CS1584;CS1580;CS1587;CS1711;CS1734;CS0618</NoWarn>
    <Version>3.0.0</Version>
    <Product>Roadkill .NET</Product>
    <Company>Roadkill .NET</Company>
    <Copyright>Copyright © Roadkill .NET</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.2" />
    <PackageReference Include="Dapper" Version="2.1.89" />
    <PackageReference Include="HtmlSanitizer" Version="9.2.1039" />
    <PackageReference Include="Lucene.Net" Version="4.8.0-beta00018" />
    <PackageReference Include="Lucene.Net.Analysis.Common" Version="4.8.0-beta00018" />
    <PackageReference Include="Lucene.Net.QueryParser" Version="4.8.0-beta00018" />
    <PackageReference Include="Markdig" Version="1.4.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.0" />
    <PackageReference Include="MongoDB.Driver" Version="3.12.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NLog" Version="6.2.1" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="System.Runtime.Caching" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Database\Schema\**\*.sql" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Roadkill.Tests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

</Project>
